name: Auto commit

on:
  push:
    branches:
      - master
      
  schedule:
  - cron: "0 * * * *"

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Modify Last Update
        run: |
          d=`date '+%Y-%m-%dT%H:%M:%SZ'`
          echo $d > LAST_UPDATED

      - name: Commit Changes
        run: |
          git config --local user.email "ifsry416@gmail.com"
          git config --local user.name "Zach"
          git add --all
          git commit -m "🤖 Automatic"
          
      - name: Push to GitHub
        run: git push
        env:
          TOKEN: ${{ secrets.TOKEN_WORKFLOWS }}
